/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs with filtering, sorting, and pagination.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Get a single job with full description.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Status
         * @description Update a job's status (applied, dismissed, etc).
         */
        patch: operations["update_status_api_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore Job
         * @description Trigger AI rescoring for a specific job.
         */
        post: operations["rescore_job_api_jobs__job_id__rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/rescore/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore All Jobs
         * @description Trigger AI rescoring for all previously scored jobs.
         */
        post: operations["rescore_all_jobs_api_jobs_rescore_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get dashboard aggregates.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trends
         * @description Get time-series and categorical data for charts.
         */
        get: operations["get_trends_api_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/dismissed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dismissal Stats
         * @description Get breakdown of dismissal reasons.
         */
        get: operations["get_dismissal_stats_api_stats_dismissed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Intelligence
         * @description Get structured market intelligence data for charts.
         */
        get: operations["get_market_intelligence_api_stats_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Insights
         * @description Get LLM-generated market intelligence narrative report (cached 1h).
         */
        get: operations["get_insights_api_stats_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Providers
         * @description Return all registered job providers for display in the UI.
         */
        get: operations["list_providers_api_pipeline_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Trigger the job collection + scoring pipeline.
         *     Returns a run_id immediately; client polls /pipeline/status/{run_id}.
         */
        post: operations["run_pipeline_api_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/status/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Status
         * @description Poll for pipeline progress. Frontend polls this every 2 seconds.
         */
        get: operations["get_pipeline_status_api_pipeline_status__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/cancel/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Pipeline
         * @description Stop a running pipeline.
         */
        post: operations["cancel_pipeline_api_pipeline_cancel__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Pipeline
         * @description Check if a pipeline is currently running for a profile.
         */
        get: operations["get_active_pipeline_api_pipeline_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/aggregator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Aggregator Status
         * @description Check if the local database is up to date with the remote aggregator.
         */
        get: operations["get_aggregator_status_api_pipeline_aggregator_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/analyze-cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Cv
         * @description Extract text from PDF and return a structured CV analysis using Claude.
         */
        post: operations["analyze_cv_api_wizard_analyze_cv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/generate-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Profile
         * @description Build search_config.yaml and profile_doc.md from structured data and user preferences.
         */
        post: operations["generate_profile_api_wizard_generate_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/refine-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine Profile
         * @description Refine template-generated profile files using LLM second pass.
         *     Falls back to original drafts on any failure.
         */
        post: operations["refine_profile_api_wizard_refine_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/save-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Profile
         * @description Write profile files to disk and ensure dependencies like scoring_philosophy.md exist.
         */
        post: operations["save_profile_api_wizard_save_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Return the contents of the example profile template files.
         */
        get: operations["get_template_api_wizard_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Profile
         * @description Create a new profile by copying the example template.
         */
        post: operations["create_profile_api_profile__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List all profile directories.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Yaml */
        get: operations["get_profile_yaml_api_profile__name__yaml_get"];
        /** Update Profile Yaml */
        put: operations["update_profile_yaml_api_profile__name__yaml_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/doc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Doc */
        get: operations["get_profile_doc_api_profile__name__doc_get"];
        /** Update Profile Doc */
        put: operations["update_profile_doc_api_profile__name__doc_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/scoring-philosophy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring Philosophy */
        get: operations["get_scoring_philosophy_api_profile__name__scoring_philosophy_get"];
        /** Update Scoring Philosophy */
        put: operations["update_scoring_philosophy_api_profile__name__scoring_philosophy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{profile}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companies */
        get: operations["get_companies_api_companies__profile__get"];
        put?: never;
        /** Add Company */
        post: operations["add_company_api_companies__profile__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{profile}/{platform}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Update Company */
        patch: operations["update_company_api_companies__profile___platform___slug__patch"];
        /** Remove Company */
        delete: operations["remove_company_api_companies__profile___platform___slug__delete"];
        options?: never;
        head?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_cv_api_wizard_analyze_cv_post */
        Body_analyze_cv_api_wizard_analyze_cv_post: {
            /** File */
            file: string;
        };
        /** CVAnalysisResponse */
        CVAnalysisResponse: {
            /** Page Count */
            page_count: number;
            /** Current Role */
            current_role: string;
            /** Experience Years */
            experience_years?: number | null;
            /** Experience Summary */
            experience_summary: string;
            /**
             * Experience
             * @default []
             */
            experience: components["schemas"]["ExperienceEntry"][];
            /**
             * Skills
             * @default {}
             */
            skills: {
                [key: string]: string[];
            };
            /**
             * Education
             * @default []
             */
            education: components["schemas"]["EducationEntry"][];
            /**
             * Portfolio
             * @default []
             */
            portfolio: components["schemas"]["PortfolioEntry"][];
            /**
             * Spoken Languages
             * @default []
             */
            spoken_languages: string[];
            /** Inferred Seniority */
            inferred_seniority: string;
            /**
             * Suggested Target Roles
             * @default []
             */
            suggested_target_roles: string[];
            /**
             * Suggested Title Patterns
             * @default {}
             */
            suggested_title_patterns: {
                [key: string]: string[];
            };
            /**
             * Suggested Description Signals
             * @default []
             */
            suggested_description_signals: string[];
            /**
             * Suggested Exclusions
             * @default []
             */
            suggested_exclusions: string[];
            /**
             * Suggested Skill Gaps
             * @default []
             */
            suggested_skill_gaps: string[];
            /**
             * Suggested Career Direction
             * @default
             */
            suggested_career_direction: string;
            /**
             * Suggested Narratives
             * @default {}
             */
            suggested_narratives: {
                [key: string]: string;
            };
            /**
             * Suggested Good Match Signals
             * @default []
             */
            suggested_good_match_signals: string[];
            /**
             * Suggested Lower Fit Signals
             * @default []
             */
            suggested_lower_fit_signals: string[];
            /**
             * Extraction Method
             * @default text
             * @enum {string}
             */
            extraction_method: "text" | "vision";
        };
        /** CompaniesResponse */
        CompaniesResponse: {
            /**
             * Greenhouse
             * @default []
             */
            greenhouse: components["schemas"]["TrackedCompanyEntry"][];
            /**
             * Lever
             * @default []
             */
            lever: components["schemas"]["TrackedCompanyEntry"][];
            /**
             * Ashby
             * @default []
             */
            ashby: components["schemas"]["TrackedCompanyEntry"][];
            /**
             * Workable
             * @default []
             */
            workable: components["schemas"]["TrackedCompanyEntry"][];
        };
        /** CompanyEntry */
        CompanyEntry: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "greenhouse" | "lever" | "ashby" | "workable";
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Company Quality Signals
             * @default []
             */
            company_quality_signals: string[];
        };
        /** CompanyUpdateRequest */
        CompanyUpdateRequest: {
            /** Name */
            name?: string | null;
            /**
             * Company Quality Signals
             * @default []
             */
            company_quality_signals: string[];
        };
        /** CompanyStat */
        CompanyStat: {
            /** Company Name */
            company_name: string;
            /** Job Count */
            job_count: number;
            /** Avg Score */
            avg_score?: number | null;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** CountryStat */
        CountryStat: {
            /** Country */
            country: string;
            /** Count */
            count: number;
        };
        /** DailyCount */
        DailyCount: {
            /** Date */
            date: string;
            /** New Jobs */
            new_jobs: number;
            /** Scored */
            scored: number;
        };
        /** DismissalStats */
        DismissalStats: {
            /**
             * Reasons
             * @default {}
             */
            reasons: {
                [key: string]: number;
            };
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** EducationEntry */
        EducationEntry: {
            /** School */
            school: string;
            /** Degree */
            degree: string;
            /** Start Year */
            start_year?: string | null;
            /** End Year */
            end_year?: string | null;
        };
        /** ExperienceEntry */
        ExperienceEntry: {
            /** Company */
            company: string;
            /** Role */
            role: string;
            /** Dates */
            dates: string;
            /** Industry */
            industry?: string | null;
            /**
             * Highlights
             * @default []
             */
            highlights: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Report */
            report: string;
            /** Generated At */
            generated_at: string;
            /** Cached */
            cached: boolean;
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Id */
            id: number;
            /** Ats Platform */
            ats_platform: string;
            /** Company Slug */
            company_slug: string;
            /** Company Name */
            company_name: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
            /** Posted At */
            posted_at?: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Score Reasoning */
            score_reasoning?: string | null;
            score_breakdown?: components["schemas"]["ScoreBreakdown"] | null;
            /** Scored At */
            scored_at?: string | null;
            /**
             * Status
             * @default new
             */
            status: string;
            /** Dismissal Reason */
            dismissal_reason?: string | null;
            /** Match Tier */
            match_tier?: string | null;
            /** Salary */
            salary?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /**
             * Is Sparse
             * @default false
             */
            is_sparse: boolean;
            /**
             * Company Quality Signals
             * @default []
             */
            company_quality_signals: string[];
            /** Description */
            description?: string | null;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Per Page */
            per_page: number;
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: number;
            /** Ats Platform */
            ats_platform: string;
            /** Company Slug */
            company_slug: string;
            /** Company Name */
            company_name: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
            /** Posted At */
            posted_at?: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Score Reasoning */
            score_reasoning?: string | null;
            score_breakdown?: components["schemas"]["ScoreBreakdown"] | null;
            /** Scored At */
            scored_at?: string | null;
            /**
             * Status
             * @default new
             */
            status: string;
            /** Dismissal Reason */
            dismissal_reason?: string | null;
            /** Match Tier */
            match_tier?: string | null;
            /** Salary */
            salary?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /**
             * Is Sparse
             * @default false
             */
            is_sparse: boolean;
            /**
             * Company Quality Signals
             * @default []
             */
            company_quality_signals: string[];
        };
        /** MarketIntelligenceResponse */
        MarketIntelligenceResponse: {
            /**
             * Skip Reason Distribution
             * @default []
             */
            skip_reason_distribution: components["schemas"]["SkipReasonStat"][];
            /**
             * Country Distribution
             * @default []
             */
            country_distribution: components["schemas"]["CountryStat"][];
            /**
             * Missing Skills
             * @default []
             */
            missing_skills: components["schemas"]["SkillCount"][];
            /**
             * Total Scored
             * @default 0
             */
            total_scored: number;
            /**
             * Apply Priority Counts
             * @default {}
             */
            apply_priority_counts: {
                [key: string]: number;
            };
            /**
             * Salary Distribution
             * @default []
             */
            salary_distribution: components["schemas"]["SalaryStat"][];
        };
        /** PipelineRunRequest */
        PipelineRunRequest: {
            /**
             * Profile
             * @default default
             */
            profile: string;
            /**
             * Sources
             * @default [
             *       "aggregator",
             *       "local"
             *     ]
             */
            sources: string[];
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** PipelineRunResponse */
        PipelineRunResponse: {
            /** Run Id */
            run_id: string;
        };
        /** PipelineStatusResponse */
        PipelineStatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error" | "cancelled" | "not_found";
            /**
             * Step
             * @default 0
             */
            step: number;
            /**
             * Step Name
             * @default
             */
            step_name: string;
            /** Detail */
            detail?: string | null;
            /** Duration */
            duration?: number | null;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            } | null;
            /**
             * Skipped Steps
             * @default []
             */
            skipped_steps: number[];
            /** Error */
            error?: string | null;
        };
        /** PortfolioEntry */
        PortfolioEntry: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Technologies
             * @default []
             */
            technologies: string[];
            /** Description */
            description?: string | null;
        };
        /** ProfileContent */
        ProfileContent: {
            /** Content */
            content: string;
        };
        /** ProfileGenerateRequest */
        ProfileGenerateRequest: {
            cv_analysis: components["schemas"]["CVAnalysisResponse"];
            user_preferences: components["schemas"]["UserPreferences"];
            /**
             * Profile Name
             * @default default
             */
            profile_name: string;
        };
        /** ProfileGenerateResponse */
        ProfileGenerateResponse: {
            /** Profile Yaml */
            profile_yaml: string;
            /** Profile Doc */
            profile_doc: string;
        };
        /** ProfileRefineRequest */
        ProfileRefineRequest: {
            cv_analysis: components["schemas"]["CVAnalysisResponse"];
            user_preferences: components["schemas"]["UserPreferences"];
            /** Draft Doc */
            draft_doc: string;
            /** Draft Yaml */
            draft_yaml: string;
        };
        /** ProfileRefineResponse */
        ProfileRefineResponse: {
            /** Profile Doc */
            profile_doc: string;
            /** Profile Yaml */
            profile_yaml: string;
            /**
             * Changes Made
             * @default []
             */
            changes_made: string[];
        };
        /** ProfileSaveRequest */
        ProfileSaveRequest: {
            /** Profile Name */
            profile_name: string;
            /** Profile Yaml */
            profile_yaml: string;
            /** Profile Doc */
            profile_doc: string;
        };
        /** ProfileTemplateResponse */
        ProfileTemplateResponse: {
            /** Profile Yaml */
            profile_yaml: string;
            /** Profile Doc */
            profile_doc: string;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Shows Aggregator Badge */
            shows_aggregator_badge: boolean;
        };
        /** SalaryStat */
        SalaryStat: {
            /** Range */
            range: string;
            /** Count */
            count: number;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * @default {
             *       "tech_stack_match": 0,
             *       "seniority_match": 0,
             *       "remote_location_fit": 0,
             *       "growth_potential": 0
             *     }
             */
            dimensions: components["schemas"]["ScoreBreakdownDimensions"];
            /**
             * Key Matches
             * @default []
             */
            key_matches: string[];
            /**
             * Red Flags
             * @default []
             */
            red_flags: string[];
            /** Fit Category */
            fit_category?: string | null;
            /**
             * Apply Priority
             * @default skip
             * @enum {string}
             */
            apply_priority: "high" | "medium" | "low" | "skip";
        };
        /** ScoreBreakdownDimensions */
        ScoreBreakdownDimensions: {
            /**
             * Tech Stack Match
             * @default 0
             */
            tech_stack_match: number;
            /**
             * Seniority Match
             * @default 0
             */
            seniority_match: number;
            /**
             * Remote Location Fit
             * @default 0
             */
            remote_location_fit: number;
            /**
             * Growth Potential
             * @default 0
             */
            growth_potential: number;
        };
        /** SkillCount */
        SkillCount: {
            /** Skill */
            skill: string;
            /** Count */
            count: number;
        };
        /** SkipReasonStat */
        SkipReasonStat: {
            /** Reason */
            reason: string;
            /** Count */
            count: number;
        };
        /** StatsOverview */
        StatsOverview: {
            /**
             * Total Jobs
             * @default 0
             */
            total_jobs: number;
            /**
             * New Today
             * @default 0
             */
            new_today: number;
            /**
             * Total New Today
             * @default 0
             */
            total_new_today: number;
            /**
             * New This Week
             * @default 0
             */
            new_this_week: number;
            /**
             * Scored
             * @default 0
             */
            scored: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Applied
             * @default 0
             */
            applied: number;
            /**
             * Dismissed
             * @default 0
             */
            dismissed: number;
            /**
             * Closed
             * @default 0
             */
            closed: number;
            /**
             * Score Distribution
             * @default {}
             */
            score_distribution: {
                [key: string]: number;
            };
            /**
             * Apply Priority Counts
             * @default {}
             */
            apply_priority_counts: {
                [key: string]: number;
            };
        };
        /** StatusUpdate */
        StatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "scored" | "applied" | "dismissed";
        };
        /** TrendsResponse */
        TrendsResponse: {
            /**
             * Daily Counts
             * @default []
             */
            daily_counts: components["schemas"]["DailyCount"][];
            /**
             * Top Skills
             * @default []
             */
            top_skills: components["schemas"]["SkillCount"][];
            /**
             * Company Stats
             * @default []
             */
            company_stats: components["schemas"]["CompanyStat"][];
            /**
             * Score Trend
             * @default []
             */
            score_trend: {
                [key: string]: unknown;
            }[];
        };
        /** TrackedCompanyEntry */
        TrackedCompanyEntry: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Company Quality Signals
             * @default []
             */
            company_quality_signals: string[];
        };
        /** UserPreferences */
        UserPreferences: {
            /**
             * Targetroles
             * @default []
             */
            targetRoles: string[];
            /**
             * Seniority
             * @default []
             */
            seniority: string[];
            /** Location */
            location: string;
            /** Workauth */
            workAuth: string;
            /**
             * Remotepref
             * @default []
             */
            remotePref: string[];
            /** Primaryremotepref */
            primaryRemotePref?: string | null;
            /** Timezonepref */
            timezonePref?: string | null;
            /**
             * Targetregions
             * @default []
             */
            targetRegions: string[];
            /**
             * Excludedregions
             * @default []
             */
            excludedRegions: string[];
            /**
             * Industries
             * @default []
             */
            industries: string[];
            /** Careerdirection */
            careerDirection: string;
            /**
             * Careergoal
             * @default stay
             */
            careerGoal: ("stay" | "pivot" | "step_up" | "broaden") | null;
            /**
             * Goodmatchsignals
             * @default []
             */
            goodMatchSignals: string[];
            /**
             * Goodmatchsignalsconfirmed
             * @default false
             */
            goodMatchSignalsConfirmed: boolean;
            /**
             * Companyqualitysignals
             * @default []
             */
            companyQualitySignals: string[];
            /**
             * Allowlowerseniorityatstrategiccompanies
             * @default false
             */
            allowLowerSeniorityAtStrategicCompanies: boolean;
            /**
             * Dealbreakers
             * @default []
             */
            dealBreakers: string[];
            /**
             * Dealbreakersconfirmed
             * @default false
             */
            dealBreakersConfirmed: boolean;
            /**
             * Enablestandardexclusions
             * @default true
             */
            enableStandardExclusions: boolean;
            /** Additionalcontext */
            additionalContext?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                profile?: string;
                status?: string | null;
                min_score?: number | null;
                max_score?: number | null;
                priority?: string | null;
                company?: string | null;
                search?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
                days?: number | null;
                is_sparse?: boolean | null;
                today_only?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_jobs__job_id__status_patch: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescore_job_api_jobs__job_id__rescore_post: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescore_all_jobs_api_jobs_rescore_all_post: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_stats_trends_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dismissal_stats_api_stats_dismissed_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DismissalStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_intelligence_api_stats_market_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketIntelligenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_api_stats_insights_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_pipeline_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"][];
                };
            };
        };
    };
    run_pipeline_api_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_status_api_pipeline_status__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_pipeline_api_pipeline_cancel__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_pipeline_api_pipeline_active_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aggregator_status_api_pipeline_aggregator_status_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_cv_api_wizard_analyze_cv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_cv_api_wizard_analyze_cv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CVAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_profile_api_wizard_generate_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_profile_api_wizard_refine_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRefineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRefineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_api_wizard_save_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_wizard_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileTemplateResponse"];
                };
            };
        };
    };
    create_profile_api_profile__name__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_yaml_api_profile__name__yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_yaml_api_profile__name__yaml_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_doc_api_profile__name__doc_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_doc_api_profile__name__doc_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_philosophy_api_profile__name__scoring_philosophy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scoring_philosophy_api_profile__name__scoring_philosophy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companies_api_companies__profile__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_company_api_companies__profile__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_companies__profile___platform___slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
                platform: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_company_api_companies__profile___platform___slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
                platform: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
