/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs with filtering, sorting, and pagination.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Get a single job with full description.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Status
         * @description Update a job's status (applied, dismissed, etc).
         */
        patch: operations["update_status_api_jobs__job_id__status_patch"];
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get dashboard aggregates.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trends
         * @description Get time-series and categorical data for charts.
         */
        get: operations["get_trends_api_stats_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/market": {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Market Intelligence */
        get: operations["get_market_intelligence_api_stats_market_get"];
    };
    "/api/stats/insights": {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_api_stats_insights_get"];
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Trigger the job collection + scoring pipeline.
         *     Returns a run_id immediately; client polls /pipeline/status/{run_id}.
         */
        post: operations["run_pipeline_api_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/status/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Status
         * @description Poll for pipeline progress. Frontend polls this every 2 seconds.
         */
        get: operations["get_pipeline_status_api_pipeline_status__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/cancel/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Pipeline
         * @description Stop a running pipeline.
         */
        post: operations["cancel_pipeline_api_pipeline_cancel__run_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_pipeline_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/aggregator/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aggregator Status */
        get: operations["get_aggregator_status_api_pipeline_aggregator_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Pipeline
         * @description Check if a pipeline is currently running for a profile.
         */
        get: operations["get_active_pipeline_api_pipeline_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List all profile directories.
         */
        get: operations["list_profiles_api_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Yaml */
        get: operations["get_profile_yaml_api_profile__name__yaml_get"];
        /** Update Profile Yaml */
        put: operations["update_profile_yaml_api_profile__name__yaml_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/doc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile Doc */
        get: operations["get_profile_doc_api_profile__name__doc_get"];
        /** Update Profile Doc */
        put: operations["update_profile_doc_api_profile__name__doc_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{name}/scoring-philosophy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring Philosophy */
        get: operations["get_scoring_philosophy_api_profile__name__scoring_philosophy_get"];
        /** Update Scoring Philosophy */
        put: operations["update_scoring_philosophy_api_profile__name__scoring_philosophy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{profile}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companies */
        get: operations["get_companies_api_companies__profile__get"];
        put?: never;
        /** Add Company */
        post: operations["add_company_api_companies__profile__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{profile}/{platform}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Company */
        delete: operations["remove_company_api_companies__profile___platform___slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompaniesResponse */
        CompaniesResponse: {
            /**
             * Greenhouse
             * @default []
             */
            greenhouse: {
                [key: string]: unknown;
            }[];
            /**
             * Lever
             * @default []
             */
            lever: {
                [key: string]: unknown;
            }[];
            /**
             * Ashby
             * @default []
             */
            ashby: {
                [key: string]: unknown;
            }[];
            /**
             * Workable
             * @default []
             */
            workable: {
                [key: string]: unknown;
            }[];
        };
        /** CompanyEntry */
        CompanyEntry: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "greenhouse" | "lever" | "ashby" | "workable";
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** CompanyStat */
        CompanyStat: {
            /** Company Name */
            company_name: string;
            /** Job Count */
            job_count: number;
            /** Avg Score */
            avg_score?: number | null;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** DailyCount */
        DailyCount: {
            /** Date */
            date: string;
            /** New Jobs */
            new_jobs: number;
            /** Scored */
            scored: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Id */
            id: number;
            /** Ats Platform */
            ats_platform: string;
            /** Company Slug */
            company_slug: string;
            /** Company Name */
            company_name: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
            /** Posted At */
            posted_at?: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Score Reasoning */
            score_reasoning?: string | null;
            score_breakdown?: components["schemas"]["ScoreBreakdown"] | null;
            /** Scored At */
            scored_at?: string | null;
            /**
             * Status
             * @default new
             */
            status: string;
            /** Dismissal Reason */
            dismissal_reason?: string | null;
            /** Match Tier */
            match_tier?: string | null;
            /** Salary */
            salary?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
            /** Description */
            description?: string | null;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /** Per Page */
            per_page: number;
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: number;
            /** Ats Platform */
            ats_platform: string;
            /** Company Slug */
            company_slug: string;
            /** Company Name */
            company_name: string;
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Url */
            url: string;
            /** Posted At */
            posted_at?: string | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Score Reasoning */
            score_reasoning?: string | null;
            score_breakdown?: components["schemas"]["ScoreBreakdown"] | null;
            /** Scored At */
            scored_at?: string | null;
            /**
             * Status
             * @default new
             */
            status: string;
            /** Salary */
            salary?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Currency */
            salary_currency?: string | null;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Shows Aggregator Badge */
            shows_aggregator_badge: boolean;
        };
        /** PipelineRunRequest */
        PipelineRunRequest: {
            /**
             * Profile
             * @default default
             */
            profile: string;
            /**
             * Sources
             * @default ["aggregator", "local"]
             */
            sources: string[];
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /** PipelineRunResponse */
        PipelineRunResponse: {
            /** Run Id */
            run_id: string;
        };
        /** PipelineStatusResponse */
        PipelineStatusResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error" | "cancelled" | "not_found";
            /**
             * Step
             * @default 0
             */
            step: number;
            /**
             * Step Name
             * @default
             */
            step_name: string;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** ProfileContent */
        ProfileContent: {
            /** Content */
            content: string;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * @default {
             *       "tech_stack_match": 0,
             *       "seniority_match": 0,
             *       "remote_location_fit": 0,
             *       "growth_potential": 0
             *     }
             */
            dimensions: components["schemas"]["ScoreBreakdownDimensions"];
            /**
             * Key Matches
             * @default []
             */
            key_matches: string[];
            /**
             * Red Flags
             * @default []
             */
            red_flags: string[];
            /**
             * Apply Priority
             * @default skip
             * @enum {string}
             */
            apply_priority: "high" | "medium" | "low" | "skip";
        };
        /** ScoreBreakdownDimensions */
        ScoreBreakdownDimensions: {
            /**
             * Tech Stack Match
             * @default 0
             */
            tech_stack_match: number;
            /**
             * Seniority Match
             * @default 0
             */
            seniority_match: number;
            /**
             * Remote Location Fit
             * @default 0
             */
            remote_location_fit: number;
            /**
             * Growth Potential
             * @default 0
             */
            growth_potential: number;
        };
        /** SkillCount */
        SkillCount: {
            /** Skill */
            skill: string;
            /** Count */
            count: number;
        };
        /** SalaryStat */
        SalaryStat: {
            /** Range */
            range: string;
            /** Count */
            count: number;
        };
        /** StatsOverview */
        StatsOverview: {
            /**
             * Total Jobs
             * @default 0
             */
            total_jobs: number;
            /**
             * New Today
             * @default 0
             */
            new_today: number;
            /**
             * New This Week
             * @default 0
             */
            new_this_week: number;
            /**
             * Scored
             * @default 0
             */
            scored: number;
            /**
             * Applied
             * @default 0
             */
            applied: number;
            /**
             * Dismissed
             * @default 0
             */
            dismissed: number;
            /**
             * Closed
             * @default 0
             */
            closed: number;
            /**
             * Score Distribution
             * @default {}
             */
            score_distribution: {
                [key: string]: number;
            };
            /**
             * Apply Priority Counts
             * @default {}
             */
            apply_priority_counts: {
                [key: string]: number;
            };
        };
        /** StatusUpdate */
        StatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "scored" | "applied" | "dismissed";
        };
        /** TrendsResponse */
        TrendsResponse: {
            /**
             * Daily Counts
             * @default []
             */
            daily_counts: components["schemas"]["DailyCount"][];
            /**
             * Top Skills
             * @default []
             */
            top_skills: components["schemas"]["SkillCount"][];
            /**
             * Company Stats
             * @default []
             */
            company_stats: components["schemas"]["CompanyStat"][];
            /**
             * Score Trend
             * @default []
             */
            score_trend: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                profile?: string;
                status?: string | null;
                min_score?: number | null;
                max_score?: number | null;
                priority?: string | null;
                company?: string | null;
                search?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
                days?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_jobs__job_id__status_patch: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_stats_trends_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_intelligence_api_stats_market_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": MarketIntelligenceResponse;
                };
            };
        };
    };
    get_insights_api_stats_insights_get: {
        parameters: {
            query?: {
                profile?: string;
                days?: number;
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        responses: {
            /** @description Successful Response */
            200: {
                content: {
                    "application/json": InsightsResponse;
                };
            };
        };
    };
    run_pipeline_api_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_status_api_pipeline_status__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_pipeline_api_pipeline_cancel__run_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_pipeline_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"][];
                };
            };
        };
    };
    get_aggregator_status_api_pipeline_aggregator_status_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_pipeline_api_pipeline_active_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_profile_yaml_api_profile__name__yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_yaml_api_profile__name__yaml_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_doc_api_profile__name__doc_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_doc_api_profile__name__doc_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_philosophy_api_profile__name__scoring_philosophy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileContent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scoring_philosophy_api_profile__name__scoring_philosophy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileContent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companies_api_companies__profile__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_company_api_companies__profile__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_company_api_companies__profile___platform___slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
                platform: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}

// --- Market Intelligence ---

export type SkillCount = {
  skill: string
  count: number
}

export type SkipReasonStat = {
  reason: string
  count: number
}

export type CountryStat = {
  country: string
  count: number
}

export type SalaryStat = {
  range: string
  count: number
}

export type MarketIntelligenceResponse = {
  skip_reason_distribution: SkipReasonStat[]
  country_distribution: CountryStat[]
  missing_skills: SkillCount[]
  salary_distribution: SalaryStat[]
  total_scored: number
  apply_priority_counts: Record<string, number>
}

export type InsightsResponse = {
  report: string
  generated_at: string
  cached: boolean
}
